# For more details, please visit https://www.github.io/docs/references/gitpod-yml
image: gitpod/workspace-postgres #1

tasks:
  - init: npm install
    command: |
      export HMR_HOST=`gp url 3000` 
      echo "Starting Dev Server..."
      npm run dev
    
ports:
  - port: 3000
    onOpen: open-browser
  - port: 5432
    onOpen: ignore

vscode:
  extensions:
    - svelte.svelte-vscode

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true